### PR TITLE
Remove code

### PR DESCRIPTION
**Pull request by j-martin**
test

### CODE REVIEW

**Comment by j-martin** [comment]
test

**Comment by j-martin** [comment]
Normal comment

**Review by j-martin — COMMENTED** [review]
This is a review comment

**Comment by j-martin** [comment]
Another normal comment

**Comment by j-martin** [comment]
Another normal comment 2

**Comment by j-martin** [comment]
test

**Comment by j-martin** [comment]
test

**Comment by j-martin** [comment]
test

**Review by j-martin — COMMENTED** [review]
ok.........

**Comment by ghost** [comment]
test

**Comment by j-martin** [comment]
Should not assign it to me.

**Comment by ghost** [comment]
test3

**Comment by ghost** [comment]
asfsajfjk

**Pull request closed without merging**
